services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:      
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: backstage
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  dbadmin:    
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_LOCAL_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data: {}
  pgadmin_data: {}